import Image from 'next/image';import Link from 'next/link';import { prisma } from '@/lib/prisma';import ArticleCard from '@/components/ArticleCard';import { defaultDescription } from '@/lib/seo';
export const revalidate=60;
export default async function Home(){const [s,posts,projects]=await Promise.all([prisma.siteSettings.findUnique({where:{id:'main'}}),prisma.post.findMany({where:{status:'PUBLISHED'},include:{category:true},orderBy:{publishedAt:'desc'},take:6}),prisma.project.findMany({where:{status:'PUBLISHED',isFeatured:true},orderBy:{sortOrder:'asc'},take:3})]);return <>
<section className="section"><div className="container" style={{display:'grid',gridTemplateColumns:'1.3fr .7fr',gap:45,alignItems:'center'}}><div><span className="eyebrow">Student • Developer • Creator</span><h1 className="title">{s?.heroTitle||"Hi, I'm DY"}<br/><span style={{background:'linear-gradient(90deg,var(--primary),var(--primary2))',WebkitBackgroundClip:'text',color:'transparent'}}>{s?.heroSubtitle||'Dipindra Yadav'}</span></h1><p className="subtitle">{s?.heroDescription||defaultDescription}</p><div className="socials" style={{marginTop:24}}><Link className="btn primary" href="/blog">Read the Blog</Link><Link className="btn" href="/projects">Explore Projects</Link></div></div><div className="card" style={{padding:12,transform:'rotate(2deg)'}}><Image src={s?.profileImage||'/images/profile.jpg'} alt="Dipindra Yadav" width={700} height={700} priority style={{width:'100%',height:'auto',borderRadius:18,display:'block'}}/></div></div></section>
<section className="section" style={{paddingTop:30}}><div className="container"><div className="eyebrow">About</div><h2 style={{fontSize:'2.3rem'}}>Learning by building.</h2><p className="subtitle" style={{maxWidth:760}}>{s?.aboutText}</p><Link className="btn" href="/about">More about me →</Link></div></section>
<section className="section"><div className="container"><div style={{display:'flex',justifyContent:'space-between',alignItems:'end',gap:15}}><div><div className="eyebrow">Selected work</div><h2 style={{fontSize:'2.3rem',margin:'8px 0'}}>Projects</h2></div><Link className="btn" href="/projects">View all</Link></div><div className="grid cards" style={{marginTop:25}}>{projects.length?projects.map(p=><div className="card" key={p.id}><span className="pill">Project</span><h3>{p.title}</h3><p className="muted">{p.description}</p><div className="taglist">{p.technologies.map(t=><span className="pill" key={t}>{t}</span>)}</div></div>):<div className="empty" style={{gridColumn:'1/-1'}}>Projects will appear here when added from the admin dashboard.</div>}</div></div></section>
<section className="section"><div className="container"><div style={{display:'flex',justifyContent:'space-between',alignItems:'end',gap:15}}><div><div className="eyebrow">From the blog</div><h2 style={{fontSize:'2.3rem',margin:'8px 0'}}>Latest articles</h2></div><Link className="btn" href="/blog">All articles</Link></div><div className="grid cards" style={{marginTop:25}}>{posts.length?posts.map(p=><ArticleCard key={p.id} post={p}/>):<div className="empty" style={{gridColumn:'1/-1'}}>Your first article will appear here.</div>}</div></div></section>
<section className="section"><div className="container card" style={{textAlign:'center',background:'linear-gradient(135deg,var(--surface),var(--surface2))'}}><div className="eyebrow">Let's connect</div><h2 style={{fontSize:'2.4rem'}}>Have an idea or a question?</h2><p className="subtitle">Send a message and it will be saved securely in the website dashboard.</p><Link className="btn primary" href="/contact">Contact me</Link></div></section>
</>}
